### ISSUE TITLE
Pull latest ConBee firmware into deconz-docker image, as official deconz .deb ships old firmware

### ISSUE THREAD

**Issue by thePaulV** [deconz-community/deconz-docker#73] opened 2022-01-02 02:55 UTC
The deconz deb for 2.13.4 includes an old Conbee II firmware, not the latest stable firmware. If you look in the deb, it includes firmware deCONZ_ConBeeII_0x26660700.bin.GCF. However, the latest listed on the [deconz firmware site](deCONZ_ConBeeII_0x26720700.bin.GCF) is deCONZ_ConBeeII_0x26720700.bin.GCF, which they announced as the stable firmware in the [2.12.6 release notes](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.12.6) back in the summer.

It would be best if this was fixed upstream, with deconz shipping the latest firmware in their deb. But in the meantime, is it possible to build in an automatic download into the community docker file to make updates easy?

As a workaround, this was my approach to pull the latest and update using docker:

Dockerfile:

```dockerfile
FROM deconzcommunity/deconz:stable

VOLUME [ "/opt/deCONZ" ]

RUN apt-get update && apt-get install -y wget && apt-get clean

RUN cd /usr/share/deCONZ/firmware/ && wget https://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x26720700.bin.GCF 

ENTRYPOINT [ "/firmware-update.sh" ]
```

Build it and run it:

``` bash
$ docker builder build . -t deconz-updater
$ docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys deconz-updater
```

**Comment by Jo-Be-Co** [comment] 2022-01-03 16:15
As you are running the entrypoint `firmware-update.sh` you could enter `deCONZ_ConBeeII_0x26720700.bin.GCF` as firmware to use.
The script will try to download this for you.
Nonetheless you are right stating that a stable firmware that old should be included so that no download is needed.

**Comment by phdelodder** [comment] 2022-01-08 12:59
The firmware is packed together with deconz, you need to create a ticket in deconz and not use the container as a workaround.

**Comment by mrandt** [comment] 2022-01-08 14:37
> As you are running the entrypoint `firmware-update.sh` you could enter `deCONZ_ConBeeII_0x26720700.bin.GCF` as firmware to use. The script will try to download this for you. Nonetheless you are right stating that a stable firmware that old should be included so that no download is needed.

The download of deCONZ_ConBeeII_0x26720700.bin.GCF does not work for me. I always get:

`Can't find 'deCONZ_ConBeeII_0x26720700.bin.GCF' neither locally nor online. Exiting ...`

I could not figure out why this happens, as I can download this file just fine using wget.

**Comment by mrandt** [comment] 2022-01-08 14:55
Please disregard my previous statement; seems to be caused by a DNS issue on my side.

**Comment by senilio** [comment] 2022-01-24 20:58
Closing. Considering the fact that firmware-update.sh already downloads the firmware of your choice, it's no use implementing a workaround for the missing firmware. The fix should happen at the source.

Thanks for the Dockerfile and build instructions though :)

**Closed by senilio** 2022-01-24 20:58 UTC
