### ISSUE TITLE
Network usage of the docker

### ISSUE THREAD

**Issue by tchristian1103** [deconz-community/deconz-docker#68] opened 2021-12-31 09:20 UTC
Is it normal that the Docker image generates so much network traffic?
If you believe the evaluation, it's about 1GB every day.

![Deconz_Docker](https://user-images.githubusercontent.com/96877363/147814830-1a337090-9126-4804-9a32-25a78dd0358b.jpg)

**Comment by phdelodder** [comment] 2021-12-31 12:22
Perhaps you could monitor the traffic on the port(s) to see what is passing through?

**Comment by javiges** [comment] 2022-01-09 15:29
I have a high use of the cpu and I think it is for the same

**Comment by senilio** [comment] 2022-01-24 21:05
Not sure what do do with this information :) The docker image does not generate any additional network traffic compared to running deCONZ standalone. Potential high CPU and/or high network I/O is likely caused by deCONZ itself. It's better to open a forum post on forums.phoscon.de or a github issue in the deCONZ repo. Closing this for now, but hopefully a solution can be found.

**Closed by senilio** 2022-01-24 21:05 UTC
